#!/bin/sh
##
## this makes the widget if the AVR32BIN environment variable
## is pointing to the directory containing avr32-gcc
##
PATH=${AVR32BIN:="cygdirve/c/Program Files/Atmel/AVR Tools/AVR32 
Studio/plugins/com.atmel.avr.toolchains.win32.x86_3.1.0.201012011657/os/win32/x86/bin"}:$PATH
export PATH
cd Release && make all
