{'application':{'type':'Application',
          'name':'Mobo Control',
    'backgrounds': [
    {'type':'Background',
          'name':'bgControlMobo',
          'title':'Mobo Control Widget',
          'size':(840, 590),

         'components': [

{'type':'StaticText', 
    'name':'stAlarmLatency', 
    'position':(650, 407), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'Alarm Latency  (x10ms)..:', 
    },

{'type':'StaticText', 
    'name':'stSWRAlarm', 
    'position':(650, 384), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'SWR Alarm (1.1 - 99.9)..:', 
    },

{'type':'TextField', 
    'name':'wxtextSWRlatency', 
    'position':(775, 402), 
    'size':(40, -1), 
    'alignment':'right', 
    'text':'wxtextSWRlatency', 
    },

{'type':'TextField', 
    'name':'wxtextSWRAlarm', 
    'position':(775, 379), 
    'size':(40, -1), 
    'alignment':'right', 
    'text':'wxtextSWRAlarm', 
    },

{'type':'StaticBox', 
    'name':'StaticBoxI2C', 
    'position':(509, 293), 
    'size':(122, 207), 
    'label':'I2C Address Control', 
    },

{'type':'Button', 
    'name':'btnI2CButton', 
    'position':(552, 474), 
    'command':'btnI2CButton', 
    'label':'Update', 
    },

{'type':'TextField', 
    'name':'wxtextad7991', 
    'position':(596, 448), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':'wxtextad7991', 
    },

{'type':'TextField', 
    'name':'wxtextad5301', 
    'position':(596, 425), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':'wxtextad5301', 
    },

{'type':'TextField', 
    'name':'wxtextTMP100', 
    'position':(596, 402), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':'wxtextTMP100', 
    },

{'type':'TextField', 
    'name':'wxtext8574l2', 
    'position':(596, 379), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':'wxtext8574l2', 
    },

{'type':'TextField', 
    'name':'wxtext8574l1', 
    'position':(596, 356), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':'wxtext8574l1', 
    },

{'type':'TextField', 
    'name':'wxtext8574m', 
    'position':(596, 333), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':'wxtext8574m', 
    },

{'type':'TextField', 
    'name':'wxtextSi570', 
    'position':(596, 310), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':'wxtextSi570', 
    },

{'type':'StaticText', 
    'name':'stAD7991', 
    'position':(518, 451), 
    'foregroundColor':(0, 0, 160, 255), 
    'text':'AD7991 ADC...:', 
    },

{'type':'StaticText', 
    'name':'stAD5301', 
    'position':(518, 428), 
    'foregroundColor':(0, 0, 160, 255), 
    'text':'AD5301 DAC...:', 
    },

{'type':'StaticText', 
    'name':'stTMP100', 
    'position':(518, 405), 
    'foregroundColor':(0, 0, 160, 255), 
    'text':'TMP100 temp..:', 
    },

{'type':'StaticText', 
    'name':'stPCF8574C', 
    'position':(518, 382), 
    'foregroundColor':(0, 0, 160, 255), 
    'text':'PCF8574 LPF2.:', 
    },

{'type':'StaticText', 
    'name':'stPCF8574B', 
    'position':(518, 359), 
    'foregroundColor':(0, 0, 160, 255), 
    'text':'PCF8574 LPF1.:', 
    },

{'type':'StaticText', 
    'name':'stPCF8574A', 
    'position':(518, 336), 
    'foregroundColor':(0, 0, 160, 255), 
    'text':'PCF8574 Mobo:', 
    },

{'type':'StaticText', 
    'name':'stSi570', 
    'position':(518, 313), 
    'foregroundColor':(0, 0, 160, 255), 
    'text':'Si570 VCXO....:', 
    },

{'type':'StaticBox', 
    'name':'readFromFirmware', 
    'position':(10, 507), 
    'size':(175, 43), 
    'label':'Read From Firmware', 
    },

{'type':'StaticBox', 
    'name':'ConfigurationSaveRestore', 
    'position':(372, 507), 
    'size':(260, 43), 
    'label':'Configuration Maintenance', 
    },

{'type':'Button', 
    'name':'btnFileSave', 
    'position':(378, 523), 
    'command':'btnFileSave', 
    'default':1, 
    'label':'Save', 
    },

{'type':'Button', 
    'name':'btnFileRestore', 
    'position':(459, 523), 
    'command':'btnFileRestore', 
    'default':1, 
    'label':'Restore', 
    },

{'type':'StaticText', 
    'name':'StaticText1', 
    'position':(193, 160), 
    'size':(187, 104), 
    'alignment':'center', 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 22}, 
    'foregroundColor':(128, 128, 128, 255), 
    'text':'SR6.3+Mobo Control Widget', 
    },

{'type':'StaticBox', 
    'name':'staticboxFirmware', 
    'position':(645, 464), 
    'size':(175, 86), 
    'label':'Firmware Control', 
    },

{'type':'StaticText', 
    'name':'FirmwareSdisplay', 
    'position':(724, 485), 
    'size':(87, -1), 
    'text':'FirmwareSdisplay', 
    },

{'type':'StaticText', 
    'name':'serialNumber', 
    'position':(652, 484), 
    'foregroundColor':(0, 0, 160, 255), 
    'text':'Serial Number:', 
    },

{'type':'StaticText', 
    'name':'FirmwareVdisplay', 
    'position':(724, 505), 
    'size':(87, -1), 
    'text':'FirmwareVdisplay', 
    },

{'type':'StaticText', 
    'name':'stFirmwareV', 
    'position':(652, 504), 
    'foregroundColor':(0, 0, 160, 255), 
    'text':'Version........:', 
    },

{'type':'StaticBox', 
    'name':'StBoxMeasuredValues', 
    'position':(23, 128), 
    'size':(163, 154), 
    },

{'type':'StaticLine', 
    'name':'StaticLine11', 
    'position':(387, 415), 
    'size':(107, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(387, 329), 
    'size':(107, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticBox', 
    'name':'bpfUpdBox', 
    'position':(387, 293), 
    'size':(107, 207), 
    },

{'type':'Button', 
    'name':'btnBPFupdate', 
    'position':(415, 389), 
    'command':'btnBPFupdate', 
    'label':'Update', 
    },

{'type':'Button', 
    'name':'btnLPFupdate', 
    'position':(414, 474), 
    'command':'btnLPFupdate', 
    'label':'Update', 
    },

{'type':'TextField', 
    'name':'LPFnr', 
    'position':(453, 421), 
    'size':(35, -1), 
    'alignment':'right', 
    'text':'LPFnr', 
    },

{'type':'StaticText', 
    'name':'stLPFupdate', 
    'position':(393, 425), 
    'text':'LPF......:', 
    },

{'type':'TextField', 
    'name':'LPFnr1', 
    'position':(438, 447), 
    'size':(50, -1), 
    'alignment':'right', 
    'text':'LPFnr1', 
    },

{'type':'StaticText', 
    'name':'stLPFcpupdate', 
    'position':(393, 451), 
    'text':'CP (kHz):', 
    },

{'type':'TextField', 
    'name':'BPFnr1', 
    'position':(438, 362), 
    'size':(50, -1), 
    'alignment':'right', 
    'text':'BPFnr1', 
    },

{'type':'StaticText', 
    'name':'stBPFcpupdate', 
    'position':(393, 365), 
    'text':'CP (kHz):', 
    },

{'type':'TextField', 
    'name':'BPFnr', 
    'position':(453, 336), 
    'size':(35, -1), 
    'alignment':'right', 
    'text':'BPFnr', 
    },

{'type':'StaticText', 
    'name':'stBPFupdate', 
    'position':(393, 341), 
    'text':'BPF......:', 
    },

{'type':'StaticBox', 
    'name':'StaticBox1', 
    'position':(409, 87), 
    'size':(125, 71), 
    },

{'type':'RadioGroup', 
    'name':'rgFrequencySpin', 
    'position':(260, 90), 
    'size':(137, 41), 
    'command':'rgFrequencySpin', 
    'items':['Hz', 'kHz', 'MHz'], 
    'label':'Spin', 
    'layout':'horizontal', 
    'max':1, 
    'stringSelection':'Hz', 
    },

{'type':'StaticBox', 
    'name':'stbPowerCalText1', 
    'position':(645, 293), 
    'size':(175, 163), 
    'label':'Power Meter and SWR Alarm', 
    },

{'type':'StaticBox', 
    'name':'stbBiasCalText', 
    'position':(386, 162), 
    'size':(149, 119), 
    'label':'Bias Calibration', 
    },

{'type':'StaticText', 
    'name':'stAuthor', 
    'position':(225, 528), 
    'size':(119, 13), 
    'alignment':'center', 
    'font':{'faceName': u'Arial', 'family': 'sansSerif', 'size': 6}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'V 0.3 2010-02-07 TF3LJ', 
    },

{'type':'Spinner', 
    'name':'biasHighSpinner', 
    'position':(466, 204), 
    'size':(60, -1), 
    'max':2540, 
    'min':0, 
    'value':350, 
    },

{'type':'Spinner', 
    'name':'biasLowSpinner', 
    'position':(466, 179), 
    'size':(60, -1), 
    'max':1000, 
    'min':0, 
    'value':20, 
    },

{'type':'StaticText', 
    'name':'bHighRawDisplay', 
    'position':(506, 234), 
    'size':(25, -1), 
    'text':'bHighRawDisplay', 
    },

{'type':'StaticText', 
    'name':'bLowRawDisplay', 
    'position':(476, 234), 
    'size':(25, -1), 
    'text':'bLowRawDisplay', 
    },

{'type':'StaticText', 
    'name':'stBiasRawText', 
    'position':(391, 234), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'Bias Raw values:', 
    },

{'type':'StaticText', 
    'name':'stBiasH', 
    'position':(391, 209), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'Bias High (mA):', 
    },

{'type':'StaticText', 
    'name':'stBiasL', 
    'position':(391, 184), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'Bias Low (mA) :', 
    },

{'type':'StaticText', 
    'name':'stFrequency', 
    'position':(10, 105), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 12}, 
    'foregroundColor':(0, 0, 255, 255), 
    'text':'Frequency', 
    },

{'type':'StaticText', 
    'name':'stSWRgauge', 
    'position':(10, 60), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 12}, 
    'foregroundColor':(0, 0, 255, 255), 
    'text':'SWR', 
    },

{'type':'StaticText', 
    'name':'stPowergauge', 
    'position':(10, 20), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 12}, 
    'foregroundColor':(0, 0, 255, 255), 
    'text':'Power', 
    },

{'type':'StaticText', 
    'name':'Vdisplay', 
    'position':(118, 210), 
    'size':(60, 13), 
    'alignment':'right', 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':'Vdisplay', 
    },

{'type':'TextField', 
    'name':'wxtextCtrlPEPwin', 
    'position':(790, 356), 
    'size':(25, -1), 
    'alignment':'right', 
    'text':'wxtextCtrlPEPwin', 
    },

{'type':'TextField', 
    'name':'wxtextCtrlPCal', 
    'position':(775, 333), 
    'size':(40, -1), 
    'alignment':'right', 
    'text':'wxtextCtrlPCal', 
    },

{'type':'TextField', 
    'name':'wxtextCtrlPScale', 
    'position':(785, 310), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':'wxtextCtrlPScale', 
    },

{'type':'StaticText', 
    'name':'stPEP', 
    'position':(650, 361), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'PEP Sample window (1-20):', 
    },

{'type':'StaticBox', 
    'name':'stbFrqOpt', 
    'position':(575, 186), 
    'size':(245, 94), 
    'label':'Bells and Whistles', 
    },

{'type':'TextField', 
    'name':'wxTextCtrlLCDoffs', 
    'position':(765, 228), 
    'size':(50, -1), 
    'text':'wxTextCtrlLCDoffs', 
    },

{'type':'TextField', 
    'name':'wxTextCtrlRotEnc', 
    'position':(765, 203), 
    'size':(50, -1), 
    'text':'wxTextCtrlRotEnc', 
    },

{'type':'StaticText', 
    'name':'stLCDoffset', 
    'position':(580, 233), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'LCD frq offset for PowerSDR-IQ (Hz):', 
    },

{'type':'StaticText', 
    'name':'stRotary', 
    'position':(580, 208), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'Rotary Encoder Resolution (32 bits)  :', 
    },

{'type':'StaticText', 
    'name':'SWRdisplay', 
    'position':(118, 185), 
    'size':(60, 13), 
    'alignment':'right', 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':'SWRdisplay', 
    },

{'type':'StaticText', 
    'name':'stSWR', 
    'position':(28, 185), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'SWR              :', 
    },

{'type':'StaticText', 
    'name':'diffDisplay', 
    'position':(444, 118), 
    'alignment':'right', 
    'text':'diffDisplay', 
    },

{'type':'StaticText', 
    'name':'stReal', 
    'position':(411, 100), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'Real:', 
    },

{'type':'StaticText', 
    'name':'PRdisplay', 
    'position':(118, 160), 
    'size':(60, 13), 
    'alignment':'right', 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':'PRdisplay', 
    },

{'type':'StaticText', 
    'name':'PFdisplay', 
    'position':(118, 135), 
    'size':(60, 13), 
    'alignment':'right', 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':'PFdisplay', 
    },

{'type':'StaticText', 
    'name':'Idisplay', 
    'position':(118, 235), 
    'size':(60, 13), 
    'alignment':'right', 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':'Idisplay', 
    },

{'type':'StaticText', 
    'name':'stDiff', 
    'position':(412, 118), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'Diff:', 
    },

{'type':'Spinner', 
    'name':'frqRealSpinner', 
    'position':(438, 97), 
    'size':(90, -1), 
    'command':'frqRealSpinner', 
    'max':54000000, 
    'min':0, 
    'value':875000, 
    },

{'type':'StaticText', 
    'name':'stHz', 
    'position':(239, 105), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 14}, 
    'text':'Hz', 
    },

{'type':'Spinner', 
    'name':'frequencySpinner', 
    'position':(93, 94), 
    'size':(147, 34), 
    'backgroundColor':(192, 192, 192, 255), 
    'font':{'style': 'bold', 'faceName': u'Calibri', 'family': 'sansSerif', 'size': 20}, 
    'foregroundColor':(128, 0, 0, 255), 
    'max':54000000, 
    'min':0, 
    'value':7020004, 
    },

{'type':'Button', 
    'name':'btnBiasButton', 
    'position':(456, 254), 
    'command':'btnBiasButton', 
    'label':'Calibrate', 
    },

{'type':'CheckBox', 
    'name':'PTTon', 
    'position':(391, 259), 
    'command':'PTTon', 
    'label':'Key TX', 
    },

{'type':'StaticText', 
    'name':'stCal', 
    'position':(650, 338), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'Cal (1-65535).............:', 
    },

{'type':'StaticText', 
    'name':'stPscale', 
    'position':(650, 315), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'Scale (1-50W) ............:', 
    },

{'type':'StaticText', 
    'name':'TMPdisplay', 
    'position':(118, 260), 
    'size':(60, 13), 
    'alignment':'right', 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':'TMPdisplay', 
    },

{'type':'StaticText', 
    'name':'stTemperature', 
    'position':(28, 260), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'Temperature  :', 
    },

{'type':'StaticText', 
    'name':'stPowerREF', 
    'position':(28, 160), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':'Power Ref      :', 
    },

{'type':'StaticText', 
    'name':'stPowerFWD', 
    'position':(28, 135), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':'Power Fwd     :', 
    },

{'type':'StaticText', 
    'name':'stCurrent', 
    'position':(28, 235), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':'PA Current     :', 
    },

{'type':'StaticText', 
    'name':'stVoltage', 
    'position':(28, 210), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':'Input Voltage  :', 
    },

{'type':'BitmapCanvas', 
    'name':'BitmapCanvasSWR', 
    'position':(69, 55), 
    'size':(470, 35), 
    'backgroundColor':(255, 255, 255, 255), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'Image', 
    'name':'Image1', 
    'position':(575, 10), 
    'size':(245, 156), 
    'file':'Po_SWR_board_beta.JPG', 
    },

{'type':'Button', 
    'name':'btnPwrButton', 
    'position':(741, 429), 
    'command':'btnPwrButton', 
    'label':'Update', 
    },

{'type':'Button', 
    'name':'btnFrqButton', 
    'position':(741, 253), 
    'command':'CMD36', 
    'label':'Update', 
    },

{'type':'Button', 
    'name':'btnSi570Calibrate', 
    'position':(440, 131), 
    'command':'btnSi570Calibrate', 
    'label':'Si570 Calibrate', 
    },

{'type':'CheckBox', 
    'name':'Repeat', 
    'position':(116, 528), 
    'size':(65, -1), 
    'command':'Repeat', 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'label':'Loop live', 
    },

{'type':'Button', 
    'name':'btnFilters', 
    'position':(391, 302), 
    'command':'btnFilters', 
    'label':'All Filters Update', 
    },

{'type':'Button', 
    'name':'btinFactoryReset', 
    'position':(541, 523), 
    'command':'btinFactoryReset', 
    'label':'Factory Reset', 
    },

{'type':'Button', 
    'name':'btnStartUSB', 
    'position':(651, 523), 
    'command':'USB', 
    'label':'Start USB', 
    },

{'type':'BitmapCanvas', 
    'name':'BitmapCanvasPWR', 
    'position':(70, 10), 
    'size':(470, 35), 
    'backgroundColor':(255, 255, 255, 255), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'Button', 
    'name':'btnRefresh', 
    'position':(17, 523), 
    'command':'Refresh', 
    'default':1, 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'label':'Poll', 
    },

{'type':'Button', 
    'name':'btnQuit', 
    'position':(740, 523), 
    'command':'Exit', 
    'label':'Quit', 
    },

{'type':'MultiColumnList', 
    'name':'LPFlist', 
    'position':(200, 300), 
    'size':(175, 200), 
    'backgroundColor':(255, 255, 255, 255), 
    'columnHeadings':[u'Filter', 'Crossover (kHz)'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':2, 
    'rules':1, 
    },

{'type':'MultiColumnList', 
    'name':'BPFlist', 
    'position':(10, 300), 
    'size':(175, 200), 
    'backgroundColor':(255, 255, 255, 255), 
    'columnHeadings':[u'Filter', 'Crossover'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':2, 
    'rules':1, 
    },

] # end components
} # end background
] # end backgrounds
} }
