################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
X_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src \
src/SOFTWARE_FRAMEWORK/UTILS/STARTUP_FILES/GCC \
src/SOFTWARE_FRAMEWORK/UTILS/DEBUG \
src/SOFTWARE_FRAMEWORK/SERVICES/USB/CLASS/HID \
src/SOFTWARE_FRAMEWORK/SERVICES/USB/CLASS/AUDIO \
src/SOFTWARE_FRAMEWORK/SERVICES/FREERTOS/Source \
src/SOFTWARE_FRAMEWORK/SERVICES/FREERTOS/Source/portable/MemMang \
src/SOFTWARE_FRAMEWORK/SERVICES/FREERTOS/Source/portable/GCC/AVR32_UC3 \
src/SOFTWARE_FRAMEWORK/DRIVERS/WDT \
src/SOFTWARE_FRAMEWORK/DRIVERS/USBB \
src/SOFTWARE_FRAMEWORK/DRIVERS/USBB/ENUM \
src/SOFTWARE_FRAMEWORK/DRIVERS/USBB/ENUM/DEVICE \
src/SOFTWARE_FRAMEWORK/DRIVERS/USART \
src/SOFTWARE_FRAMEWORK/DRIVERS/TWIM \
src/SOFTWARE_FRAMEWORK/DRIVERS/TC \
src/SOFTWARE_FRAMEWORK/DRIVERS/SSC/I2S \
src/SOFTWARE_FRAMEWORK/DRIVERS/RTC \
src/SOFTWARE_FRAMEWORK/DRIVERS/PM \
src/SOFTWARE_FRAMEWORK/DRIVERS/PDCA \
src/SOFTWARE_FRAMEWORK/DRIVERS/INTC \
src/SOFTWARE_FRAMEWORK/DRIVERS/GPIO \
src/SOFTWARE_FRAMEWORK/DRIVERS/FLASHC \
src/SOFTWARE_FRAMEWORK/DRIVERS/EIC \
src/SOFTWARE_FRAMEWORK/BOARDS/SDRwdgtLite \
src/SOFTWARE_FRAMEWORK/ASM \

